### ISSUE TITLE
Validating reject_bad_trial

### ISSUE THREAD

**Issue by annesodub** [ABRBABY/ABRBABY_matlab#92]
Estelle tested on the dataset : [eba359ccc9f3243c4a4b2f0381c9a5aaa0462407](https://github.com/ABRBABY/ABRBABY_matlab/commit/eba359ccc9f3243c4a4b2f0381c9a5aaa0462407)

**Comment by estellerv** [comment]
validated !

**Comment by annesodub** [comment]
Please Estelle Check the results of the new version  on one or two participants. d15de30a9fd1444e523f8c6d13b4d6d6d1b9a0e2

**Comment by estellerv** [comment]
I detected something wrong in the code. The issue is about the init_beg_bloc variable that allows the rejection of the 3 first STD of each bloc.
L.73: when running the function with the 'ERP' sequence (OPTIONS.analysis = 'ERP'), the variable flag_sequence marks all HF indices at 0. However, at line 73, the flag is reversed (~flag_sequence), thus the 3 first HF are marked 0 instead of the 3 first STD. 
I suggest that we add a condition so that beginning of bloc is marked only when OPTIONS.analysis = 'ERP' (and with the right flag).
What do you think @annesodub ?

**Comment by annesodub** [comment]
Hi Estelle, 

Nice catch! I just inverted the order of a couple of lines (https://github.com/ABRBABY/ABRBABY_matlab/pull/95), this should fix the issue. Please let me know if this does not work.

**Comment by estellerv** [comment]
Hi @annesodub 

I tested again, it works for ERPs but only if the '~' is deleted before the variable 'flag_sequence' at line 70. I let you do the modification on your branch.

However, there is another issue when running the function from FFR script (with OPTIONS.analysis = 'FFR'). I noted that the number of trials rejected was different from the older version of the FFR function (rej_and_prepare_input_brainstem). I found the reason why: in the older version, we ran the epoch rejection function only on the ABR electrode. In the current version, the function is run on the 16 cortical electrodes, which is not what we want for the FFR. We need to specify which electrodes are considered depending on the OPTIONS.analysis value.

**Comment by annesodub** [comment]
Hi, 

The flag for beginning of block is now corrected. 

In addition, I removed the unsued OPTIONS filed .bloc which I replaced by a useful one: beg_bloc_to_rej which can be used only for ERP analysis (if the field does not exist it will stay empty). 

I left the possibility to write such a column for FFR analysis if the variable exist in OPTION (in case it would be interesting to remove the first trials of HF as well ;-) **Please discuss this with Clement**) 

As for the electrodes to take into account for auto trial rejection, yes the electrodes selection (and time window) was taken from previous step:

```
  %Get eeg_elec and win_of_interest from RFE set of parameters
    eeg_elec = EEG.history_stepA.eeg_elec ;
    win_of_interest = EEG.history_stepA.win_of_interest ;

``` 
I fixed the selection of the electrode ABR for FFR analysis, and left the time window from previous step because I think it make sense and add a field to OPTIONS to select different sets of electrodes. 

Please let me know if anything goes wrong.

**Comment by estellerv** [comment]
Hi,
I tested the code. The improvement you made on both reref_filter_epoch and reject_bad_trials scripts is nice, however, I have noted 2 things:
- the output variable in reref_filter_epoch must be initialized before the "if" section (l.6 to 9), otherwise it returns an error
- l.7: the '/n' is backwards -> '\n'

Otherwise, everything works perfectly! Thanks !
